Доработан skyforge, отредактирован README
 - Использование OverlayFS заменено на UnionFS, так как OverlayFS
не работает и ругается что не создан для этой цели
(по крайней мере на Debian 10);
 - Доработана команда MULTISTRAP: появился аргумент RETRY_WITH,
используется например если для доступа к репозиторию для MULTISTRAP-а
нужен нестандартный GPG ключ (ключ нельзя установить до MULTISTRAP так
как rootfs ещё не создана);
 - Доработана команда INSTALL: теперь указывается папка назначения,
используется например чтобы добавить в собираемую rootfs файлы из
локальной папки;
 - Доработана команда IFACE_STATIC: добавлена возможность указать DNS;
 - Исправлено вычисление хешей и статуса RERUN_FOLLOWING при
возвращении из Skyfile (при использовании INCLUDE);
 - Добавлена возможность выключать оверлеи если они поддерживаются;
 - Убраны сообщения от umount и mount в логе сборки;
 - Добавлена вспомогательная команда STOP: для использования во время
написания и отладки сборки;
 - Исправлен код возвращаемый командой RUN: ранее все действия
выполняемые через RUN считались успешными;
 - В случае возникновения ошибки в команде SH всегда возвращается 1
(и останавливается сборка);
 - В случае ошибки при выполнении команды REMOVE возвращается 1
(и останавливается сборка);
 - Доработана команда HOSTNAME: добавляет локальный ip в /etc/hosts;
 - Доработана команда LOCALE: теперь можно указать несколько локалей,
основной считается первая;
 - Действие replay переименовано в reset, для большего соответствия выполняемым
действиям;
 - В команде DPKG_CONFIGURE silent переименован в noninteractive в
соответствии с терминологией Debian;
 - Добавлено действие rebuild - выполняет полную пересборку (просто
чтобы писать меньше команд в консоли);
 - Исправлено и улучшено форматирование в README, подписаны аргументы
команд.

diff --git a/skyforge b/skyforge
--- a/skyforge
+++ b/skyforge
@@ -1,5 +1,7 @@
 #!/bin/bash
-# Copyright © 2016 Andrew Andrianov <andrew@ncrmnt.org>
+# Copyright ©:
+#   2016 Andrew Andrianov <andrew@ncrmnt.org>
+#   2020 Pavel Kuznetsov <kuznetsov@lotes-tm.ru>
 # This work is free. You can redistribute it and/or modify it under the terms
 # of MIT license. See LICENSE.TXT bundled along with the software for details
 
@@ -11,9 +13,9 @@ SAVE_STEPS=0
 WORKDIR=.forge
 DRY_RUN=0
 NEED_RESTORE=0
-RERUN_FOLLOWING=0
 CLEANUP=
-SKIP_CHECKPOINTING="EXT4IMAGE EXT3IMAGE EXT2IMAGE STORE DISKIMAGE"
+SKIP_CHECKPOINTING="EXT4IMAGE EXT3IMAGE EXT2IMAGE DISKIMAGE"
+OVERLAY=1
 
 if [ -z "$SKYFILE" ]; then
   SKYFILE=Skyfile
@@ -23,7 +25,9 @@ skyforge_init()
 {
   [ -d $WORKDIR ] || mkdir -p $WORKDIR
   [ -d $WORKDIR/.bottom ] || mkdir -p $WORKDIR/.bottom
-  echo "$WORKDIR/.bottom" > $WORKDIR/.stack
+  [ -f $WORKDIR/.rerun ] && rm $WORKDIR/.rerun
+  [ -f $WORKDIR/.stack ] && rm $WORKDIR/.stack
+  echo "$WORKDIR/.bottom=RO" > $WORKDIR/.stack
 
   if [ -f $WORKDIR/.save_steps ]; then
     SAVE_STEPS=`cat $WORKDIR/.save_steps`
@@ -33,18 +37,20 @@ skyforge_init()
     echo "[W] SkyForge will tarball state on each step. This will require a lot of space"
   fi
 
+  [ $OVERLAY == "0" ] && return 0
   skyforge_check_overlayfs
-  modprobe overlay
+  #modprobe overlay
   if [ "$?" != "0" ]; then
-    echo "[W] No OverlayFS support in current kernel. Fast snapshots unavailable. Read docs"
+    echo "[W] No unionfs support. Fast snapshots unavailable. Read docs"
     return 0
   fi
-
+    return 0
 }
 
 skyforge_check_overlayfs()
 {
-  [ "`grep overlay /proc/filesystems |wc -l`" != "1" ] && return 1
+  [ $OVERLAY == "0" ] && return 1
+  [ "`unionfs &> /dev/null`" == "127" ] && return 1
   return 0
 }
 
@@ -68,7 +74,6 @@ skyforge_hash()
 
 skyforge_cleanup()
 {
-
 #Not the most optimal, but gets the job done
   echo "Reading the sacred $SKYFILE..."
   for hash in `ls $WORKDIR|grep -v tgz`; do
@@ -129,16 +134,17 @@ skyforge_get_chroot_mounts()
 
 skyforge_bind_unmount()
 {
-  umount ./rootfs/proc/
-  umount ./rootfs/sys/
-  umount ./rootfs/dev/pts
-  umount ./rootfs/dev/
+  umount ./rootfs/proc/ 2> /dev/null
+  umount ./rootfs/sys/ 2> /dev/null
+  umount ./rootfs/dev/pts 2> /dev/null
+  umount ./rootfs/dev/ 2> /dev/null
   true
   for mpoint in `skyforge_get_chroot_mounts`; do
-    umount $mpoint
+    umount $mpoint 2> /dev/null || return 1
   done
   if [ "`skyforge_get_chroot_mounts`" != "" ]; then
     echo "ERROR: We failed to unmount some filesystems from chroot, please do it manually"
+    return 1
   fi
 }
 
@@ -148,7 +154,7 @@ skyforge_unmount_rootfs()
   #Therefore - do recursive cleanup
   true
   while [ $? -eq "0" ]; do
-    umount rootfs 2>/dev/null
+    umount rootfs 2> /dev/null
   done
 }
 
@@ -186,9 +192,9 @@ skyforge_directory_is_mountpoint()
 skyforge_overlay_add_layer()
 {
   skyforge_directory_is_mountpoint rootfs
-
   if [ "$?" == "0" ]; then
     skyforge_unmount_rootfs
+    killall unionfs 2> /dev/null
   fi
 
   skyforge_check_overlayfs
@@ -202,15 +208,17 @@ skyforge_overlay_add_layer()
 
   STACK="`cat $WORKDIR/.stack`"
   if [ "$PREVIOUS" != "" ]; then
-    STACK="$WORKDIR/.$PREVIOUS.data:$STACK"
+    STACK="$WORKDIR/.$PREVIOUS.data=RO:$STACK"
   fi
 
   echo "$STACK" > $WORKDIR/.stack
-  mkdir -p $WORKDIR/.work
+  echo "$STACK"
+  # mkdir -p $WORKDIR/.work
   mkdir -p $WORKDIR/.$CURRENT.data
-  mount -t overlay overlay -o \
-  lowerdir=$STACK,upperdir=$WORKDIR/.$CURRENT.data,workdir=$WORKDIR/.work \
-  rootfs
+  #mount -t overlay overlay -o \
+  #lowerdir=$STACK,upperdir=$WORKDIR/.$CURRENT.data,workdir=$WORKDIR/.work \
+  #rootfs
+  unionfs -o cow -o allow_other,use_ino,suid,dev,nonempty $WORKDIR/.$CURRENT.data=RW:$STACK rootfs
 }
 
 skyforge_execute_step()
@@ -232,7 +240,7 @@ skyforge_execute_step()
   fi
 
   #Status output. Should we skip this step?
-  if [ -f $WORKDIR/$CURRENT ] && [ "$RERUN_FOLLOWING" -ne "1" ]; then
+  if [ -f $WORKDIR/$CURRENT ] && [ ! -f $WORKDIR/.rerun ]; then
     echo "[S] $PRINTHASH | $* "
     NEED_RESTORE=1
     #Make sure to add it as overlay before bailing out
@@ -241,11 +249,14 @@ skyforge_execute_step()
   fi
 
   echo "[R] $PRINTHASH | $*"
-  RERUN_FOLLOWING=1
+  touch $WORKDIR/.rerun
 
   if [ "$DRY_RUN" -eq "1" ]; then
     return 0
   fi
+
+  [ -d $WORKDIR/.$CURRENT.data ] && rm -rf $WORKDIR/.$CURRENT.data
+  [ -f $WORKDIR/$CURRENT ] && rm -rf $WORKDIR/$CURRENT
 
   #Add a fresh overlay
   skyforge_overlay_add_layer $CURRENT
@@ -279,27 +290,41 @@ skyforge_run_skyfile()
     exit 1
   fi
 
-  cat $1| grep -v '^$' | grep -v '^#' | sed "s/'/\\'/g" | \
-    while IFS= read line; do
-      case "`echo $line | awk '{print $1}'`" in
+  while IFS= read -r line; do
+    case "`echo $line | awk '{print $1}'`" in
       INCLUDE)
-        skyforge_run_skyfile `echo $line | awk '{print $2}'`
+        skyforge_run_skyfile `echo $line | awk '{print $2}'` || exit 1
+        [ -f $WORKDIR/.skyfile_last_current ] && CURRENT=$(cat $WORKDIR/.skyfile_last_current) && rm $WORKDIR/.skyfile_last_current
         ;;
       ARTIFACT)
-        echo "`echo $line | awk '{print $2}'`" >> $WORKDIR/.cleanup
+        name=`echo $line | awk '{print $2}'`
+        grep -cq "$line" $WORKDIR/.cleanup || echo "$name" >> $WORKDIR/.cleanup
         ;;
       *)
-        skyforge_execute_step "$line"
+        skyforge_execute_step "$line" || exit 1
         ;;
-      esac
-  done
+    esac
+  done < <(cat $1 | grep -v '^$' | grep -v '^#' | sed "s/'/\\'/g")
+  echo $CURRENT > $WORKDIR/.skyfile_last_current
 }
 
 MULTISTRAP()
 {
   multistrap -d rootfs -a ${1} -f ${2}
   R=$?
-  [ "$R" != "0" ] && return $R
+  RETRY=""
+  if [ $# -gt 3 ] && [ $3 == "RETRY_WITH" ]; then
+    RETRY="${@:4}"
+  fi
+  if [ "$R" != "0" ]; then
+    if [ ! -z "$RETRY" ]; then
+        echo "[i] multistrap failed, try to rescue by RETRY_WITH: $RETRY"
+        $RETRY
+        MULTISTRAP $1 $2
+        return $?
+    fi
+    return $R
+  fi
 
   #We have to map here from debian architecture names to qemu-static ones
   #That's a f*cking mess ;(
@@ -336,36 +361,47 @@ MULTISTRAP()
     cp `which qemu-$ARCH-static` rootfs/usr/bin/
     echo "[I] Installing /usr/bin/qemu-$ARCH-static to target"
   fi
+}
 
+STOP()
+{
+  return 1
 }
 
 RUN()
 {
-  skyforge_bind_mount
+  skyforge_bind_mount || return 1
   echo "$*" | chroot rootfs
+  R=$?
   skyforge_kill_chroot_processes
   skyforge_bind_unmount
+  return $R
 }
 
 SH()
 {
-  $*
+  $* || return 1
 }
 
 INSTALL()
 {
-  cp $1 rootfs/$1
+  mkdir -p rootfs$2 || return 1
+  cp $1 rootfs$2 || return 1
 }
 
 REMOVE()
 {
-  rm -f rootfs/$1
+  rm -f rootfs/$1 || return 1
 }
 
 STORE()
 {
-  tar cpzf $1 -C rootfs .
+  SH [ -d temp ] && rm -r temp
+  SH cp -rp rootfs/ temp/
+  SH rm -r temp/.unionfs-fuse
+  tar cpzf $1 -C temp .
   echo "$1" >> $WORKDIR/.cleanup
+  echo "-r temp/" >> $WORKDIR/.cleanup
 }
 
 PASSWD()
@@ -376,12 +412,26 @@ PASSWD()
 HOSTNAME()
 {
     RUN "echo \"$1\" > /etc/hostname"
+    RUN "echo \"127.0.0.1 $1\" >> /etc/hosts"
 }
 
 LOCALE()
 {
-  RUN "echo \"$*\" >> /etc/locale.gen"
-  RUN locale-gen
+  if [ $(echo $@ | grep -c ",") -ne "0" ]; then
+    REMOVE /etc/locale.gen
+    IFS=','
+    read -ra locs <<< "$@"
+    for loc in "${locs[@]}"; do
+        RUN "echo \"$loc\" >> /etc/locale.gen"
+        RUN "echo -e 'LANG=\"$1\"\\nLANGUAGE=\"$1\"\\n' > /etc/default/locale"
+    done
+    RUN locale-gen
+    IFS=' '
+  else
+    RUN "echo \"$*\" >> /etc/locale.gen"
+    RUN locale-gen
+    RUN "echo -e 'LANG=\"$1\"\\nLANGUAGE=\"$1\"\\n' > /etc/default/locale"
+  fi
 }
 
 IFACE_STATIC()
@@ -391,6 +441,7 @@ IFACE_STATIC()
   RUN "echo   address $2 >> /etc/network/interfaces.d/$1"
   RUN "echo   netmask $3 >> /etc/network/interfaces.d/$1"
   RUN "echo   gateway $4 >> /etc/network/interfaces.d/$1"
+  RUN "echo   dns-nameservers $5 >> /etc/network/interfaces.d/$1"
 }
 
 IFACE_DHCP()
@@ -459,7 +510,7 @@ ALLOW_SERVICE_START()
 DPKG_CONFIGURE()
 {
   case "$1" in
-    silent)
+    noninteractive)
       ICMD="DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true"
     ;;
     interactive)
@@ -473,10 +524,11 @@ DPKG_CONFIGURE()
     ;;
   esac
   DENY_SERVICE_START
-  RUN $ICMD LC_ALL=C LANGUAGE=C LANG=C /var/lib/dpkg/info/dash.preinst install
-  RUN $ICMD LC_ALL=C LANGUAGE=C LANG=C dpkg --configure -a
+  RUN $ICMD dpkg --configure -a
+  R=$?
   ALLOW_SERVICE_START
   export SKYFORGE_SYSTEM_CONFIGURED=yes
+  return $R
 }
 
 LDSOFIXUP()
@@ -515,7 +567,6 @@ ADD_DEB()
         done
     fi
   done
-  RUN apt-get -f -y --force-yes install
   ALLOW_SERVICE_START
 }
 
@@ -591,7 +642,7 @@ usage()
   echo "  purge          - Remove all stuff created by skyforge"
   echo "  tarball        - Developer mode: Save tgz snapshots for every step"
   echo "  status         - Print current steps and their status"
-  echo "  replay hash    - Replay all actions starting with the one with specified hash"
+  echo "  reset hash     - Replay all actions starting with the one with specified hash"
   echo "  mount          - Mount the OverlayFS to ./rootfs"
   echo "TIP: You can specify the Skyfile to run with SKYFILE=mySkyfile skyforge blah"
   exit 1
@@ -606,6 +657,20 @@ fi
 if [ "$#" -eq "0" ]; then
   usage $0
 fi
+
+echo "$@" | grep -qe "\-\-no-overlay"
+if [ "$?" -eq "0" ]; then
+  OVERLAY=0
+  echo "[i] Overlays was disabled by command line args"
+fi
+
+ps aux > $WORKDIR/.temp && awk "/unionfs/ && !/$WORKDIR\// {exit_code=1;} END{ exit !exit_code}" < $WORKDIR/.temp && [ $OVERLAY -eq "1" ]
+if [ $? -eq "0" ]; then
+    rm $WORKDIR/.temp
+    echo "Running unionfs detected, please umount its or use --no-overlay"
+    exit 1
+fi
+rm $WORKDIR/.temp
 
 skyforge_init
 case "$1" in
@@ -622,7 +687,7 @@ case "$1" in
     skyforge_kill_chroot_processes
     skyforge_bind_unmount
     skyforge_unmount_rootfs
-    skyforge_run_skyfile $SKYFILE
+    skyforge_run_skyfile $SKYFILE || exit 1
     echo "[I] Your rootfs is now forged!"
   ;;
   purge)
@@ -630,10 +695,8 @@ case "$1" in
     skyforge_bind_unmount
 
     [ -f "$WORKDIR/.cleanup" ] && cat $WORKDIR/.cleanup | while read line; do
-      if [ -f $line ]; then
-        echo "[i] Removing build artifact: $line"
-        rm -f "$line"
-      fi
+      echo "[i] Removing build artifact: $line"
+      rm -f $line || true
     done
 
     echo "[i] Unmounting and removing target rootfs"
@@ -659,12 +722,16 @@ case "$1" in
     DRY_RUN=1
     skyforge_run_skyfile $SKYFILE
     ;;
-  replay)
+  reset)
     rm -f ${WORKDIR}/${2}*
     ;;
   mount)
     DRY_RUN=1
     skyforge_run_skyfile $SKYFILE
+    ;;
+  rebuild)
+    $0 purge
+    $0 build
     ;;
   *)
     usage $1
