skyforge: SYMLINK2COPY: Properly handle recursive symlinks
Signed-off-by: Andrew Andrianov <andrew@ncrmnt.org>

diff --git a/skyforge b/skyforge
--- a/skyforge
+++ b/skyforge
@@ -29,7 +29,7 @@ skyforge_init()
   fi
 
   if [ "$SAVE_STEPS" -eq "1" ]; then
-    echo "[W] SkyForge will tarball state on each state. This will require a lot of space"
+    echo "[W] SkyForge will tarball state on each step. This will require a lot of space"
   fi
 
   skyforge_check_overlayfs
@@ -347,24 +347,41 @@ APT_KEY()
   RUN wget -O- $1 \| apt-key add -
 }
 
+#$1
+skyforge_replace_symlink_with_copy()
+{
+  link="$1"
+
+  if [ ! -L "$abstarget" ]; then
+    return
+  fi
+
+  dir=$(dirname "$link")
+  reltarget=$(readlink "$link")
+  if [[ $reltarget == /* ]]; then
+      abstarget=.$reltarget
+  else
+      abstarget=$dir/$reltarget
+  fi
+
+  rm -f "$link"
+
+  if [ -L "$abstarget" ]; then
+    skyforge_replace_symlink_with_copy $abstarget
+  fi
+
+  cp -af "$abstarget" "$link" || {
+      # on failure, restore the symlink
+      rm -rfv "$link"
+      ln -sfv "$reltarget" "$link"
+  }
+}
+
 SYMLINK2COPY()
 {
   cd rootfs
   for link in `find . -type l`; do
-    dir=$(dirname "$link")
-    reltarget=$(readlink "$link")
-    if [[ $reltarget == /* ]]; then
-        abstarget=.$reltarget
-    else
-        abstarget=$dir/$reltarget
-    fi
-
-    rm -f "$link"
-    cp -af "$abstarget" "$link" || {
-        # on failure, restore the symlink
-        rm -rfv "$link"
-        ln -sfv "$reltarget" "$link"
-    }
+    skyforge_replace_symlink_with_copy "$link"
   done
   cd ..
 }
@@ -385,6 +402,7 @@ SYMLINK2RELATIVE()
           COUNT=$((COUNT-1))
       done
       REL="${SLASHES}${DIR}/${NAME}"
+      REL="`echo $REL | sed 's/\/\//\//g'`"
       cd "`dirname $l`"
       ln -sfv $REL "`basename $l`"
       cd "$CURDIR"
